useTabs: false
tabWidth: 4
printWidth: 100
singleQuote: true
trailingComma: all
endOfLine: lf
plugins:
    - prettier-plugin-svelte
    - prettier-plugin-tailwindcss
overrides:
    - files: '*.svelte'
      options:
          parser: 'svelte'
